### ISSUE TITLE
drawerToggle() function didn't get called 

### ISSUE THREAD

**Issue by ZahraAsgharzadeh** [darshan2509/DKNavigationDrawer#3]
Hi dear , I love your menu , but drawerToggle() func didn't get called and I don't know why . I did all things step by step as you said but this is my problem . 
What can I do to fix it ???

**Comment by darshan2509** [comment]
Hi, 
Check if you connected BarButtonItem to action or connected button inside the BarButtonItem to action. You have to connect the button highlighted in blue as per below image.

Thanks

![Screen Shot 2019-04-25 at 2 02 56 PM](https://user-images.githubusercontent.com/16682748/56721612-e2245a80-6762-11e9-867f-e4689b9c2682.png)

**Comment by ZahraAsgharzadeh** [comment]
I did the same , and also I put break point in the action and it comes there , but the break point didn't stop at the start of drawerToggle() function , I don't know why .

**Comment by ZahraAsgharzadeh** [comment]
even the viewDidload() method didn't get called in DKNavDrawer class :(

**Comment by darshan2509** [comment]
can you share your code? i will look into it.

**Comment by ZahraAsgharzadeh** [comment]
```//
//  availableController.swift
//  test
//
//  Created by zahra asg  on 8/12/18.
//  Copyright © 2018 zahra asg. All rights reserved.
//

import UIKit

class availableController: UIViewController, DKNavDrawerDelegate {
    func dkNavDrawerSelection(_ selectionIndex: Int) {
        print(selectionIndex)
    }    
    @IBOutlet private weak var segmentOutlet: UISegmentedControl!
    @IBOutlet private weak var imageGif: UIImageView!
    @IBOutlet private weak var cardview: CardView!
    @IBOutlet private weak var menuBtn: UIButton!

    
    var rootNav: DKNavDrawer?
    
    
    @IBAction func menuAction(_ sender: Any) {
        self.rootNav?.drawerToggle()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        rootNav = (navigationController as? DKNavDrawer)
        rootNav?.dkNavDrawerDelegate = self
        
        self.navigationItem.title = "title"
    }
}
```
here is my code , and also the subclass of my UINavigationController is DKNavDrawer

**Comment by ZahraAsgharzadeh** [comment]
what is my problem ?

**Comment by darshan2509** [comment]
[DKNavigationDrawer.zip](https://github.com/darshan2509/DKNavigationDrawer/files/3116330/DKNavigationDrawer.zip)

Kindly check the above project.

**Comment by ZahraAsgharzadeh** [comment]
oh, It works , I presented this controller from another controller and it causes the problem , it solved with performing segue . 
and now I have another question , 
how can I make it to appear from right side not left ???

**Comment by darshan2509** [comment]
Yes you can, you will have to make minor changes to the code. 
If possible i will send you the code by today.

**Comment by darshan2509** [comment]
> // Left Navigation Drawer
>         //        outFrame = CGRect(x: CGFloat(-menuWidth), y: CGFloat(0), width: CGFloat(menuWidth), height: CGFloat(meunHeight))
>         //       inFrame = CGRect(x: CGFloat(0), y: CGFloat(0), width: CGFloat(menuWidth), height: CGFloat(meunHeight))
>         
>         // Right Navigation Drawer
>         outFrame = CGRect(x: CGFloat(wind.frame.size.width ), y: CGFloat(0), width: CGFloat(menuWidth), height: CGFloat(meunHeight))
>         inFrame = CGRect(x: wind.frame.width - CGFloat(menuWidth), y: CGFloat(0), width: CGFloat(menuWidth), height: CGFloat(meunHeight))


Just add/repalce this code in setUpDrawer() method.
Note : I have not tested left navigation, i think it won't give you any issues but you will have to make changes in the pan gesture method.

**Comment by ZahraAsgharzadeh** [comment]
Thanks a million 🌹
